services:
  image-api:
    build: .
    container_name: image-api
    restart: unless-stopped
    ports:
      - "8082:8082"

    environment:

      # =========================
      # DATABASE (service externo)
      # =========================
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/control_image
      SPRING_DATASOURCE_USERNAME: desenv
      SPRING_DATASOURCE_PASSWORD: 123ateo9

      # =========================
      # PROFILE
      # =========================
      SPRING_PROFILES_ACTIVE: docker

      # =========================
      # KEYCLOAK (serviço externo)
      # =========================
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://auth.animal-adoption.com.br/realms/MY_KEYCLOAK

      # =========================
      # SCHEMA
      # =========================
      SCHEMA_NAME: file

      # =========================
      # MINIO / S3 (serviço externo)
      # =========================
      STORAGE_S3_ENDPOINT: http://minio:9000
      STORAGE_S3_ACCESS_KEY: admin
      STORAGE_S3_SECRET_KEY: minio123ateo9
      STORAGE_S3_BUCKET: images
      STORAGE_S3_REGION: us-east-1

      # =========================
      # BASE URL da própria API
      # =========================
      BASE_URL: https://minio.animal-adoption.com.br
    extra_hosts:
      - "auth.animal-adoption.com.br:192.168.18.7"
    networks:
      - my-infra-docker
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.api-animal-adoption.rule=Host(`image-api.animal-adoption.com.br`)"
      - "traefik.http.routers.api-animal-adoption.entrypoints=websecure"
      - "traefik.http.routers.api-animal-adoption.tls=true"
      - "traefik.http.routers.api-animal-adoption.tls.certresolver=letsencrypt"

      - "traefik.http.services.api-animal-adoption.loadbalancer.server.port=8083"

networks:
  my-infra-docker:
    external: true