services:
  image-api:
    build: .
    container_name: image-api
    restart: unless-stopped

    environment:

      # =========================
      # DATABASE
      # =========================
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/control_image
      SPRING_DATASOURCE_USERNAME: desenv
      SPRING_DATASOURCE_PASSWORD: 123ateo9

      # =========================
      # PROFILE
      # =========================
      SPRING_PROFILES_ACTIVE: docker

      # =========================
      # KEYCLOAK
      # =========================
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: https://auth.animal-adoption.com.br/realms/MY_KEYCLOAK

      # =========================
      # SCHEMA
      # =========================
      SCHEMA_NAME: file

      # =========================
      # MINIO / S3
      # =========================
      STORAGE_S3_ENDPOINT: http://minio:9000
      STORAGE_S3_ACCESS_KEY: admin
      STORAGE_S3_SECRET_KEY: minio123ateo9
      STORAGE_S3_BUCKET: images
      STORAGE_S3_REGION: us-east-1

      # =========================
      # BASE URL DA IMAGE API
      # =========================
      BASE_URL: https://image-api.animal-adoption.com.br

    networks:
      - my-infra-docker

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.image-api.rule=Host(`image-api.animal-adoption.com.br`)"
      - "traefik.http.routers.image-api.entrypoints=websecure"
      - "traefik.http.routers.image-api.tls=true"
      - "traefik.http.routers.image-api.tls.certresolver=letsencrypt"

      - "traefik.http.services.image-api.loadbalancer.server.port=8082"

networks:
  my-infra-docker:
    external: true